### ISSUE TITLE
Introduce metric for auth.log

### ISSUE THREAD

**Issue by ppp0** [cargomedia/bipbip#104]
To register unusual login activity, using the `log_parser` plugin:

Example config:
```
plugin: log-parser
path: /var/log/auth.log
matchers:
 -
  name: admin_session
  regexp: 'Accepted publickey for admin'
 -
  name: sudo_session_admin
  regexp: 'pam_unix(sudo:session): session opened for user root by admin'
```
